### ISSUE TITLE
How to Handle Flexible Array Members?

### ISSUE THREAD

**Issue by 4tuw2tuv0** [Z572/guile-wlroots#3]
Hey! There are a few `struct`s in the wlroots codebase which make use of a flexible array member. I wasn't able to find any examples tackling it in guile-wlroots but do you know how to tackle such scenarios? From what I can tell, Guile Bytevectors isn't able to handle them, yet, and requires for `bs:vector` to always receive a vector size.

**Comment by Z572** [comment]
see
https://github.com/Z572/guile-wlroots/blob/3e6113a86ab0b69aac5c9a0ed1141d5ea8b3a5d0/wlroots/types/seat.scm#L437-L448

**Comment by Z572** [comment]
and https://github.com/Z572/guile-wlroots/blob/3e6113a86ab0b69aac5c9a0ed1141d5ea8b3a5d0/wlroots/types/keyboard.scm#L49-L72

**Comment by Z572** [comment]
just use `#:allocation #:virtual` and `(bs:vector length %bsd)`at runtime

**Comment by 4tuw2tuv0** [comment]
So that makes sense for a class's field but I meant in the context of `bs:struct`.

In the case of `wlr-keyboard`, the struct is defined with a size for `keycodes` (`WLR_KEYBOARD_KEYS_CAP`) so, correspondingly, you've got

https://github.com/Z572/guile-wlroots/blob/3e6113a86ab0b69aac5c9a0ed1141d5ea8b3a5d0/wlroots/types.scm#L742

But what do we do in the case of https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/types/wlr_linux_dmabuf_v1.c#L41, where no size has been specified? I may just be missing something but, since `bs:vector` expects some sort of size to be given, I'm not sure.

**Comment by Z572** [comment]
https://github.com/TaylanUB/scheme-bytestructures/issues/41 , maybe can set it use (bs:unknow), use `#:allocation #:virtual` for all slot, and use `(bs:vector length %bsd)` at `tranches` slot, or use guile's parse-c-struct.
